### ISSUE TITLE
Grammatical error in the description of custom lightness scale option

### ISSUE THREAD

**Issue by saharshbhansali** [PotatoProject/PotatoFries#10]
![Screenshot_20220213-010454_Lawnchair](https://user-images.githubusercontent.com/75335566/153749905-40e31b6c-eac3-4743-b8fc-c8864bbcead6.png)
"If ~enables~ enabled, it allows using the custom lightness scale"

**Comment by saharshbhansali** [comment]
I'd like to help resolve this, but I'm not able to find the appropriate file that has the description text.
I'm not quite proficient with Flutter, but I doubt this would require the use of anything too advanced.

**Comment by dvd-bnc** [comment]
bruh i forgot to fix this, i noticed it way earlier when i was rewriting the thing and i always forgot to update. If you'd like to make a PR you can change the string in [here](https://github.com/PotatoProject/PotatoFries/blob/frico-release/lib/backend/data.dart#L267)
